### ISSUE TITLE
Taking over translation maintenance

### ISSUE THREAD

**Issue by bugron** [javascript-tutorial/hy.javascript.info#66]
Hi @vhgn,
I hope you are doing fine!

@ArthurHakobyan and I would like to team up with you to boost the progress of Armenian translation. In case you are unable to work on the translation anymore, could you, please, make me the maintainer of this repo?
Thanks in advance for your response.

FYI @iliakan

**Comment by iliakan** [comment]
Hope to hear from current maintainers soon!

**Comment by iliakan** [comment]
Hi,

You're maintainers now, with all the access in place. 
Got the invite to the org?

**Comment by bugron** [comment]
Accepted! Thanks @iliakan !

**Comment by ArthurHakobyan** [comment]
Accepted. Thanks
